### ISSUE TITLE
Support for dynamic creation of Items

### ISSUE THREAD

**Issue by walison17** [linw1995/data_extractor#56]
currently is not possible to create items that inherit from `AbstractComplexExtractor`, the code breaks when `_check_field_overwrites_method()` is executed

**Comment by linw1995** [comment]
Is there any code cases that reproduce your problem? Please describe your code, express what you expect and what error it actually produces.

**Comment by walison17** [comment]
```python
from data_extractor import Item, Field, JSONExtractor


type("Foo", (Item,), {"bar": Field(JSONExtractor("bar"))})
```
This code above raises:
```python
AssertionError: Can't find the source of <class '__main__.Foo'>.
```

Ps.: I am using python 3.8.2

**Comment by linw1995** [comment]
This bug is fixed. Thanks for your help. @walison17

**Comment by walison17** [comment]
Thanks @linw1995
